
SET @user_a_id=0;
SET @user_b_id=0;
SET @user_c_id=0;
SET @user_d_id=0;

-- 각 유형별로 남자 5 여자 5명씩 삽입 --
-- 각각 rate 는 1, 3, 5, 7, 9 --

INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFJ_rate1', 1, NOW(), 'done', 1, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFJ_rate3', 1, NOW(), 'done', 1, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFJ_rate5', 1, NOW(), 'done', 1, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFJ_rate7', 1, NOW(), 'done', 1, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFJ_rate9', 1, NOW(), 'done', 1, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFJ_rate_1', 1, NOW(), 'done', 1, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFJ_rate_3', 1, NOW(), 'done', 1, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFJ_rate_5', 1, NOW(), 'done', 1, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFJ_rate_7', 1, NOW(), 'done', 1, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFJ_rate_9', 1, NOW(), 'done', 1, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTJ_rate1', 1, NOW(), 'done', 2, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTJ_rate3', 1, NOW(), 'done', 2, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTJ_rate5', 1, NOW(), 'done', 2, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTJ_rate7', 1, NOW(), 'done', 2, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTJ_rate9', 1, NOW(), 'done', 2, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTJ_rate_1', 1, NOW(), 'done', 2, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTJ_rate_3', 1, NOW(), 'done', 2, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTJ_rate_5', 1, NOW(), 'done', 2, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTJ_rate_7', 1, NOW(), 'done', 2, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTJ_rate_9', 1, NOW(), 'done', 2, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFP_rate1', 1, NOW(), 'done', 3, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFP_rate3', 1, NOW(), 'done', 3, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFP_rate5', 1, NOW(), 'done', 3, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFP_rate7', 1, NOW(), 'done', 3, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESFP_rate9', 1, NOW(), 'done', 3, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFP_rate_1', 1, NOW(), 'done', 3, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFP_rate_3', 1, NOW(), 'done', 3, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFP_rate_5', 1, NOW(), 'done', 3, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFP_rate_7', 1, NOW(), 'done', 3, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESFP_rate_9', 1, NOW(), 'done', 3, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTP_rate1', 1, NOW(), 'done', 4, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTP_rate3', 1, NOW(), 'done', 4, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTP_rate5', 1, NOW(), 'done', 4, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTP_rate7', 1, NOW(), 'done', 4, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ESTP_rate9', 1, NOW(), 'done', 4, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTP_rate_1', 1, NOW(), 'done', 4, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTP_rate_3', 1, NOW(), 'done', 4, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTP_rate_5', 1, NOW(), 'done', 4, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTP_rate_7', 1, NOW(), 'done', 4, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ESTP_rate_9', 1, NOW(), 'done', 4, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFJ_rate1', 1, NOW(), 'done', 5, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFJ_rate3', 1, NOW(), 'done', 5, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFJ_rate5', 1, NOW(), 'done', 5, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFJ_rate7', 1, NOW(), 'done', 5, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFJ_rate9', 1, NOW(), 'done', 5, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFJ_rate_1', 1, NOW(), 'done', 5, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFJ_rate_3', 1, NOW(), 'done', 5, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFJ_rate_5', 1, NOW(), 'done', 5, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFJ_rate_7', 1, NOW(), 'done', 5, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFJ_rate_9', 1, NOW(), 'done', 5, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTJ_rate1', 1, NOW(), 'done', 6, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTJ_rate3', 1, NOW(), 'done', 6, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTJ_rate5', 1, NOW(), 'done', 6, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTJ_rate7', 1, NOW(), 'done', 6, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTJ_rate9', 1, NOW(), 'done', 6, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTJ_rate_1', 1, NOW(), 'done', 6, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTJ_rate_3', 1, NOW(), 'done', 6, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTJ_rate_5', 1, NOW(), 'done', 6, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTJ_rate_7', 1, NOW(), 'done', 6, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTJ_rate_9', 1, NOW(), 'done', 6, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFP_rate1', 1, NOW(), 'done', 7, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFP_rate3', 1, NOW(), 'done', 7, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFP_rate5', 1, NOW(), 'done', 7, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFP_rate7', 1, NOW(), 'done', 7, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISFP_rate9', 1, NOW(), 'done', 7, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFP_rate_1', 1, NOW(), 'done', 7, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFP_rate_3', 1, NOW(), 'done', 7, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFP_rate_5', 1, NOW(), 'done', 7, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFP_rate_7', 1, NOW(), 'done', 7, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISFP_rate_9', 1, NOW(), 'done', 7, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTP_rate1', 1, NOW(), 'done', 8, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTP_rate3', 1, NOW(), 'done', 8, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTP_rate5', 1, NOW(), 'done', 8, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTP_rate7', 1, NOW(), 'done', 8, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ISTP_rate9', 1, NOW(), 'done', 8, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTP_rate_1', 1, NOW(), 'done', 8, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTP_rate_3', 1, NOW(), 'done', 8, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTP_rate_5', 1, NOW(), 'done', 8, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTP_rate_7', 1, NOW(), 'done', 8, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ISTP_rate_9', 1, NOW(), 'done', 8, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFJ_rate1', 1, NOW(), 'done', 9, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFJ_rate3', 1, NOW(), 'done', 9, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFJ_rate5', 1, NOW(), 'done', 9, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFJ_rate7', 1, NOW(), 'done', 9, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFJ_rate9', 1, NOW(), 'done', 9, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFJ_rate_1', 1, NOW(), 'done', 9, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFJ_rate_3', 1, NOW(), 'done', 9, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFJ_rate_5', 1, NOW(), 'done', 9, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFJ_rate_7', 1, NOW(), 'done', 9, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFJ_rate_9', 1, NOW(), 'done', 9, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTJ_rate1', 1, NOW(), 'done', 10, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTJ_rate3', 1, NOW(), 'done', 10, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTJ_rate5', 1, NOW(), 'done', 10, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTJ_rate7', 1, NOW(), 'done', 10, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTJ_rate9', 1, NOW(), 'done', 10, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTJ_rate_1', 1, NOW(), 'done', 10, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTJ_rate_3', 1, NOW(), 'done', 10, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTJ_rate_5', 1, NOW(), 'done', 10, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTJ_rate_7', 1, NOW(), 'done', 10, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTJ_rate_9', 1, NOW(), 'done', 10, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFP_rate1', 1, NOW(), 'done', 11, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFP_rate3', 1, NOW(), 'done', 11, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFP_rate5', 1, NOW(), 'done', 11, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFP_rate7', 1, NOW(), 'done', 11, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENFP_rate9', 1, NOW(), 'done', 11, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFP_rate_1', 1, NOW(), 'done', 11, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFP_rate_3', 1, NOW(), 'done', 11, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFP_rate_5', 1, NOW(), 'done', 11, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFP_rate_7', 1, NOW(), 'done', 11, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENFP_rate_9', 1, NOW(), 'done', 11, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTP_rate1', 1, NOW(), 'done', 12, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTP_rate3', 1, NOW(), 'done', 12, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTP_rate5', 1, NOW(), 'done', 12, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTP_rate7', 1, NOW(), 'done', 12, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_ENTP_rate9', 1, NOW(), 'done', 12, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTP_rate_1', 1, NOW(), 'done', 12, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTP_rate_3', 1, NOW(), 'done', 12, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTP_rate_5', 1, NOW(), 'done', 12, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTP_rate_7', 1, NOW(), 'done', 12, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_ENTP_rate_9', 1, NOW(), 'done', 12, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFJ_rate1', 1, NOW(), 'done', 13, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFJ_rate3', 1, NOW(), 'done', 13, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFJ_rate5', 1, NOW(), 'done', 13, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFJ_rate7', 1, NOW(), 'done', 13, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFJ_rate9', 1, NOW(), 'done', 13, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFJ_rate_1', 1, NOW(), 'done', 13, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFJ_rate_3', 1, NOW(), 'done', 13, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFJ_rate_5', 1, NOW(), 'done', 13, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFJ_rate_7', 1, NOW(), 'done', 13, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFJ_rate_9', 1, NOW(), 'done', 13, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTJ_rate1', 1, NOW(), 'done', 14, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTJ_rate3', 1, NOW(), 'done', 14, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTJ_rate5', 1, NOW(), 'done', 14, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTJ_rate7', 1, NOW(), 'done', 14, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTJ_rate9', 1, NOW(), 'done', 14, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTJ_rate_1', 1, NOW(), 'done', 14, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTJ_rate_3', 1, NOW(), 'done', 14, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTJ_rate_5', 1, NOW(), 'done', 14, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTJ_rate_7', 1, NOW(), 'done', 14, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTJ_rate_9', 1, NOW(), 'done', 14, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFP_rate1', 1, NOW(), 'done', 15, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFP_rate3', 1, NOW(), 'done', 15, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFP_rate5', 1, NOW(), 'done', 15, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFP_rate7', 1, NOW(), 'done', 15, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INFP_rate9', 1, NOW(), 'done', 15, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFP_rate_1', 1, NOW(), 'done', 15, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFP_rate_3', 1, NOW(), 'done', 15, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFP_rate_5', 1, NOW(), 'done', 15, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFP_rate_7', 1, NOW(), 'done', 15, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INFP_rate_9', 1, NOW(), 'done', 15, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTP_rate1', 1, NOW(), 'done', 16, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTP_rate3', 1, NOW(), 'done', 16, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTP_rate5', 1, NOW(), 'done', 16, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTP_rate7', 1, NOW(), 'done', 16, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('여_INTP_rate9', 1, NOW(), 'done', 16, 1, 9, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTP_rate_1', 1, NOW(), 'done', 16, 1, 1, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTP_rate_3', 1, NOW(), 'done', 16, 1, 3, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTP_rate_5', 1, NOW(), 'done', 16, 1, 5, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTP_rate_7', 1, NOW(), 'done', 16, 1, 7, NOW());
INSERT INTO users(nick_name, registration_confirmed, registration_confirmed_at, registration_phase, animal_id, sex, rate,  el_time) VALUES ('남_INTP_rate_9', 1, NOW(), 'done', 16, 1, 9, NOW());


-- 강현이에게 하트를 준 유저 --


-- 강현이에게 더블 하트를 준 유저 --




