"""0706_rate

Revision ID: 0109673c95ef
Revises: 500ed2e644aa
Create Date: 2020-07-06 00:00:47.572913

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = '0109673c95ef'
down_revision = '500ed2e644aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate')
    # ### end Alembic commands ###
