"""0926_notify

Revision ID: 02970cb36bc2
Revises: ba8fa9c368ba
Create Date: 2020-09-26 14:13:10.379096

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02970cb36bc2'
down_revision = 'ba8fa9c368ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('body', mysql.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('notifications', sa.Column('fire', sa.BOOLEAN(), nullable=True))
    op.add_column('notifications', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), server_default='0', nullable=True))
    op.add_column('notifications', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['to_user_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'users', ['from_user_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'to_user_id')
    op.drop_column('notifications', 'read')
    op.drop_column('notifications', 'from_user_id')
    op.drop_column('notifications', 'fire')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'body')
    # ### end Alembic commands ###
