"""0515term

Revision ID: 0e31a9a8cd8c
Revises: 84e48a72074f
Create Date: 2020-05-15 16:26:30.949661

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e31a9a8cd8c'
down_revision = '84e48a72074f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('required', sa.BOOLEAN(), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'type_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type_group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'type_groups', ['type_group'], ['id'])
    op.drop_column('terms', 'required')
    # ### end Alembic commands ###
