"""0514sms

Revision ID: 18b163762c75
Revises: 54f8c3fc5156
Create Date: 2020-05-14 17:30:15.704938

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18b163762c75'
down_revision = '54f8c3fc5156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_key', mysql.CHAR(length=80), nullable=True),
    sa.Column('auth_value', mysql.CHAR(length=10), nullable=True),
    sa.Column('phone_num', mysql.CHAR(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expiration', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('company', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('education', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('height', mysql.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('location1', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('location2', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('occupation_confirmed', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('occupation_confirmed_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('phone_registered', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.TEXT(), nullable=True))
    op.drop_column('users', 'phone_registered')
    op.drop_column('users', 'occupation_confirmed_at')
    op.drop_column('users', 'occupation_confirmed')
    op.drop_column('users', 'location2')
    op.drop_column('users', 'location1')
    op.drop_column('users', 'height')
    op.drop_column('users', 'education')
    op.drop_column('users', 'company')
    op.drop_table('sms_auth')
    # ### end Alembic commands ###
