"""05_11

Revision ID: 1d4e321d5999
Revises: c8b29c202a09
Create Date: 2020-05-11 15:34:59.327289

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d4e321d5999'
down_revision = 'c8b29c202a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('party_id', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('until', sa.DATE(), nullable=True),
    sa.Column('party_name', mysql.CHAR(length=20), nullable=True),
    sa.Column('kind', mysql.CHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_apple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', mysql.CHAR(length=80), nullable=False),
    sa.Column('party_name', mysql.TEXT(), nullable=False),
    sa.Column('party_email', mysql.TEXT(), nullable=True),
    sa.Column('party_picture', mysql.TEXT(), nullable=True),
    sa.Column('refresh_token', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    op.create_table('oauth_facebook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', mysql.CHAR(length=50), nullable=False),
    sa.Column('party_name', mysql.TEXT(), nullable=False),
    sa.Column('party_picture', mysql.TEXT(), nullable=True),
    sa.Column('party_email', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    op.create_table('oauth_google',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', mysql.CHAR(length=50), nullable=False),
    sa.Column('party_name', mysql.TEXT(), nullable=False),
    sa.Column('party_email', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    op.create_table('oauth_kakao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', mysql.CHAR(length=50), nullable=False),
    sa.Column('party_name', mysql.TEXT(), nullable=False),
    sa.Column('party_email', mysql.TEXT(), nullable=True),
    sa.Column('party_picture', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_kakao')
    op.drop_table('oauth_google')
    op.drop_table('oauth_facebook')
    op.drop_table('oauth_apple')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
