"""08_10match_open

Revision ID: 208fdff7ad80
Revises: 4cdf3ef7eb2a
Create Date: 2020-08-10 17:24:44.734624

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = '208fdff7ad80'
down_revision = '4cdf3ef7eb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('opened', sa.BOOLEAN(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'opened')
    # ### end Alembic commands ###
