"""0724_from_id

Revision ID: 29e170f95e52
Revises: d823d2af626a
Create Date: 2020-07-24 23:48:20.463999

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29e170f95e52'
down_revision = 'd823d2af626a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('phone', mysql.TEXT(), nullable=True))
    op.add_column('matches', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_from_user_id'), 'matches', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_matches_to_user_id'), 'matches', ['to_user_id'], unique=False)
    op.drop_constraint('matches_ibfk_1', 'matches', type_='foreignkey')
    op.drop_constraint('matches_ibfk_2', 'matches', type_='foreignkey')
    op.drop_index('ix_matches_man_id', table_name='matches')
    op.drop_index('ix_matches_woman_id', table_name='matches')
    op.create_foreign_key(None, 'matches', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'matches', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('matches', 'man_id')
    op.drop_column('matches', 'woman_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('woman_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('man_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_ibfk_2', 'matches', 'users', ['woman_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('matches_ibfk_1', 'matches', 'users', ['man_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_matches_woman_id', 'matches', ['woman_id'], unique=False)
    op.create_index('ix_matches_man_id', 'matches', ['man_id'], unique=False)
    op.drop_index(op.f('ix_matches_to_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_from_user_id'), table_name='matches')
    op.drop_column('matches', 'to_user_id')
    op.drop_column('matches', 'from_user_id')
    op.drop_column('blacklist', 'phone')
    # ### end Alembic commands ###
