"""0619_star

Revision ID: 399aee118a81
Revises: a9598583633d
Create Date: 2020-06-19 18:08:52.962129

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '399aee118a81'
down_revision = 'a9598583633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.add_column('stars', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stars_from_user_id'), 'stars', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_stars_to_user_id'), 'stars', ['to_user_id'], unique=False)
    op.create_foreign_key(None, 'stars', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(None, 'stars', 'users', ['to_user_id'], ['id'])
    op.drop_column('stars', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('user_id', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.drop_index(op.f('ix_stars_to_user_id'), table_name='stars')
    op.drop_index(op.f('ix_stars_from_user_id'), table_name='stars')
    op.drop_column('stars', 'to_user_id')
    op.drop_column('stars', 'from_user_id')
    # ### end Alembic commands ###
