"""0704_animal_summary

Revision ID: 3bda25d54050
Revises: 45af72b180ff
Create Date: 2020-07-04 16:18:26.822920

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bda25d54050'
down_revision = '45af72b180ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('best_partners', LaboratoryTypes.TextTuple(), nullable=True))
    op.add_column('animals', sa.Column('summary', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'summary')
    op.drop_column('animals', 'best_partners')
    # ### end Alembic commands ###
