"""0704_type_group

Revision ID: 45af72b180ff
Revises: f3ce5fe0bcef
Create Date: 2020-07-04 12:32:13.328209

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = '45af72b180ff'
down_revision = 'f3ce5fe0bcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('type_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'animals', 'type_groups', ['type_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.drop_column('animals', 'type_group_id')
    # ### end Alembic commands ###
