"""0614

Revision ID: 461dc95e2b3b
Revises: f00bb70ba0ec
Create Date: 2020-06-14 09:46:33.549128

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461dc95e2b3b'
down_revision = 'f00bb70ba0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('animal_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'personality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personality', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_2', 'users', 'users', ['personality'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'animal_id')
    # ### end Alembic commands ###
