"""0628el_time

Revision ID: 4843e23ff6a3
Revises: ee799a3b13d6
Create Date: 2020-06-28 20:06:43.709166

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4843e23ff6a3'
down_revision = 'ee799a3b13d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('el_time', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'el_time')
    # ### end Alembic commands ###
