"""0704_animal_summary2

Revision ID: 500ed2e644aa
Revises: 3bda25d54050
Create Date: 2020-07-04 16:27:03.247164

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = '500ed2e644aa'
down_revision = '3bda25d54050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
