"""0629_frozen

Revision ID: 514d49145f78
Revises: 5b5b52d90ff9
Create Date: 2020-06-29 17:56:24.450244

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514d49145f78'
down_revision = '5b5b52d90ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_correlations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_animal_id', mysql.INTEGER(), nullable=True),
    sa.Column('to_animal_ids', LaboratoryTypes.IntTuple(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('animal_corelations')
    op.add_column('users', sa.Column('frozen_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('frozen_until', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.TEXT(), nullable=True))
    op.drop_column('users', 'frozen_until')
    op.drop_column('users', 'frozen_at')
    op.create_table('animal_corelations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_animal_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_animal_ids', mysql.TEXT(), nullable=True),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('animal_correlations')
    # ### end Alembic commands ###
