"""term

Revision ID: 54f8c3fc5156
Revises: f458918a525a
Create Date: 2020-05-14 11:35:07.662340

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54f8c3fc5156'
down_revision = 'f458918a525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbti_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', mysql.TEXT(), nullable=True),
    sa.Column('determinant', mysql.CHAR(length=5), nullable=True),
    sa.Column('positive', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agreed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animals', sa.Column('mbti', mysql.CHAR(length=50), nullable=True))
    op.add_column('animals', sa.Column('name', mysql.CHAR(length=50), nullable=True))
    op.drop_column('users', 'hp')
    op.drop_column('users', 'mp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('animals', 'name')
    op.drop_column('animals', 'mbti')
    op.drop_table('terms_agreements')
    op.drop_table('terms')
    op.drop_table('mbti_questions')
    # ### end Alembic commands ###
