"""0906_life_style

Revision ID: 57ba692d8dca
Revises: 08e9a9c89df4
Create Date: 2020-09-06 16:03:44.950013

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57ba692d8dca'
down_revision = '08e9a9c89df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_style_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answers', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_style_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questions', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('admins_ibfk_1', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('terms_agreements_ibfk_2', 'terms_agreements', type_='foreignkey')
    op.create_foreign_key(None, 'terms_agreements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_ibfk_5', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_3', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'oauth_kakao', ['oauth_kakao_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'oauth_naver', ['oauth_naver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'oauth_google', ['oauth_google_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_3', 'users', 'oauth_google', ['oauth_google_id'], ['id'])
    op.create_foreign_key('users_ibfk_2', 'users', 'oauth_naver', ['oauth_naver_id'], ['id'])
    op.create_foreign_key('users_ibfk_5', 'users', 'oauth_kakao', ['oauth_kakao_id'], ['id'])
    op.drop_constraint(None, 'terms_agreements', type_='foreignkey')
    op.create_foreign_key('terms_agreements_ibfk_2', 'terms_agreements', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_ibfk_1', 'admins', 'users', ['user_id'], ['id'])
    op.drop_table('life_style_questions')
    op.drop_table('life_style_answers')
    # ### end Alembic commands ###
