"""0628corelation

Revision ID: 5b5b52d90ff9
Revises: 4843e23ff6a3
Create Date: 2020-06-29 00:23:27.568502

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b5b52d90ff9'
down_revision = '4843e23ff6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_corelations', sa.Column('from_animal_id', mysql.INTEGER(), nullable=True))
    op.add_column('animal_corelations', sa.Column('to_animal_ids', LaboratoryTypes.IntTuple(), nullable=True))
    op.add_column('animal_corelations', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_corelations', 'weight')
    op.drop_column('animal_corelations', 'to_animal_ids')
    op.drop_column('animal_corelations', 'from_animal_id')
    # ### end Alembic commands ###
