"""0712_report

Revision ID: 6ec35fcacb5e
Revises: 4ede39a3c64e
Create Date: 2020-07-12 21:18:10.638659

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ec35fcacb5e'
down_revision = '4ede39a3c64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('memo', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_from_user_id'), 'reports', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_reports_to_user_id'), 'reports', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_to_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_from_user_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
