"""08_10_heart_match

Revision ID: 803cfd291413
Revises: 208fdff7ad80
Create Date: 2020-08-10 18:50:18.727483

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '803cfd291413'
down_revision = '208fdff7ad80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hearts_ibfk_3', 'hearts', type_='foreignkey') # 3 은 뭐 하는 걸까...
    op.drop_constraint('hearts_ibfk_4', 'hearts', type_='foreignkey')
    op.drop_column('hearts', 'match_id')
    op.add_column('matches', sa.Column('heart_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('from_to_user_id', 'matches', ['from_user_id', 'to_user_id'])
    op.create_foreign_key(None, 'matches', 'hearts', ['heart_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint('from_to_user_id', 'matches', type_='unique')
    op.drop_column('matches', 'heart_id')
    op.add_column('hearts', sa.Column('match_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hearts_ibfk_3', 'hearts', 'matches', ['match_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
