"""1003_notification

Revision ID: 83eb4e1a2244
Revises: 02970cb36bc2
Create Date: 2020-10-03 10:21:11.779995

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83eb4e1a2244'
down_revision = '02970cb36bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification')
    # ### end Alembic commands ###
