"""0506_rate_required_server_default

Revision ID: a4fa9df93e5c
Revises: 543302cde053
Create Date: 2020-08-06 23:23:46.545247

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = 'a4fa9df93e5c'
down_revision = '543302cde053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
