"""0706_rate_decimal

Revision ID: c1e004d8f852
Revises: 0109673c95ef
Create Date: 2020-07-06 00:01:34.207165

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = 'c1e004d8f852'
down_revision = '0109673c95ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
