"""08_10_coupon

Revision ID: c2932ba30b40
Revises: 803cfd291413
Create Date: 2020-08-10 20:27:34.715763

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2932ba30b40'
down_revision = '803cfd291413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.CHAR(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed', sa.BOOLEAN(), server_default='0', nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('redeemed_at', mysql.DATETIME(), nullable=True),
    sa.Column('hp', sa.Integer(), server_default='0', nullable=True),
    sa.Column('mp', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_coupons_user_id'), 'coupons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_user_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
