"""first_revision3

Revision ID: c9e88e0e18ee
Revises: 6d7c2748a3f4
Create Date: 2020-04-29 20:57:19.707461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from libs.database.types import LaboratoryTypes

# revision identifiers, used by Alembic.
revision = 'c9e88e0e18ee'
down_revision = '6d7c2748a3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_corelations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hearts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('double', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('occupation', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.Column('pictures', LaboratoryTypes.TextTuple(), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.CHAR(length=20), nullable=True),
    sa.Column('location', mysql.TEXT(), nullable=True),
    sa.Column('body_shape', mysql.TEXT(), nullable=True),
    sa.Column('religion', mysql.TEXT(), nullable=True),
    sa.Column('hobby', mysql.TEXT(), nullable=True),
    sa.Column('speciality', mysql.TEXT(), nullable=True),
    sa.Column('interest', mysql.TEXT(), nullable=True),
    sa.Column('drink', mysql.TEXT(), nullable=True),
    sa.Column('cigarette', mysql.TEXT(), nullable=True),
    sa.Column('hp', mysql.INTEGER(), nullable=True),
    sa.Column('mp', mysql.INTEGER(), nullable=True),
    sa.Column('registered_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_access', mysql.DATETIME(), nullable=True),
    sa.Column('fcm_token', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_point_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('hp', mysql.INTEGER(), nullable=True),
    sa.Column('mp', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hp', mysql.INTEGER(), nullable=True),
    sa.Column('mp', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_points')
    op.drop_table('user_point_transactions')
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_table('hearts')
    op.drop_table('animal_corelations')
    # ### end Alembic commands ###
