"""0724_hard_delete

Revision ID: d823d2af626a
Revises: 6ec35fcacb5e
Create Date: 2020-07-24 22:56:45.598204

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd823d2af626a'
down_revision = '6ec35fcacb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hearts', 'match_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'hearts', 'matches', ['match_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('matches_ibfk_2', 'matches', type_='foreignkey')
    op.drop_constraint('matches_ibfk_1', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['man_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'matches', 'users', ['woman_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('reports_ibfk_2', 'reports', type_='foreignkey')
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('stars_ibfk_1', 'stars', type_='foreignkey')
    op.drop_constraint('stars_ibfk_2', 'stars', type_='foreignkey')
    op.create_foreign_key(None, 'stars', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'stars', 'users', ['to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.create_foreign_key('stars_ibfk_2', 'stars', 'users', ['to_user_id'], ['id'])
    op.create_foreign_key('stars_ibfk_1', 'stars', 'users', ['from_user_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_1', 'reports', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key('reports_ibfk_2', 'reports', 'users', ['to_user_id'], ['id'])
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_ibfk_1', 'matches', 'users', ['woman_id'], ['id'])
    op.create_foreign_key('matches_ibfk_2', 'matches', 'users', ['man_id'], ['id'])
    op.drop_constraint(None, 'hearts', type_='foreignkey')
    op.alter_column('hearts', 'match_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
