"""0623_timestamp

Revision ID: ee799a3b13d6
Revises: ffdef0352b0d
Create Date: 2020-06-23 16:10:37.815819

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = 'ee799a3b13d6'
down_revision = 'ffdef0352b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
