"""0706_decimal_precision

Revision ID: eeabef0e1544
Revises: c1e004d8f852
Create Date: 2020-07-06 00:10:18.758177

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = 'eeabef0e1544'
down_revision = 'c1e004d8f852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
