"""admin

Revision ID: f00bb70ba0ec
Revises: 0e31a9a8cd8c
Create Date: 2020-05-29 13:02:45.084250

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f00bb70ba0ec'
down_revision = '0e31a9a8cd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.CHAR(length=30), server_default='', nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('avatar', mysql.TEXT(), nullable=True),
    sa.Column('role', mysql.CHAR(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
