"""0618

Revision ID: f185b8b43637
Revises: 461dc95e2b3b
Create Date: 2020-06-18 20:38:10.196359

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes


# revision identifiers, used by Alembic.
revision = 'f185b8b43637'
down_revision = '461dc95e2b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_animals_mbti'), 'animals', ['mbti'], unique=True)
    op.add_column('hearts', sa.Column('accpeted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hearts', 'accpeted')
    op.drop_index(op.f('ix_animals_mbti'), table_name='animals')
    # ### end Alembic commands ###
