"""1004_heart_message

Revision ID: f2f03308a5d1
Revises: 83eb4e1a2244
Create Date: 2020-10-04 12:19:40.389519

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f03308a5d1'
down_revision = '83eb4e1a2244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearts', sa.Column('message', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hearts', 'message')
    # ### end Alembic commands ###
