"""0701_user

Revision ID: f3ce5fe0bcef
Revises: 514d49145f78
Create Date: 2020-07-01 20:43:49.156002

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3ce5fe0bcef'
down_revision = '514d49145f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'animal_correlations', 'animals', ['from_animal_id'], ['id'])
    op.add_column('users', sa.Column('age', mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_constraint(None, 'animal_correlations', type_='foreignkey')
    # ### end Alembic commands ###
