"""0514_q

Revision ID: f454cdf86693
Revises: 18b163762c75
Create Date: 2020-05-14 21:27:53.391149

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f454cdf86693'
down_revision = '18b163762c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.Column('acronym', mysql.CHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupation_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation_type', mysql.CHAR(length=20), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animals', sa.Column('main_profile', mysql.TEXT(), nullable=True))
    op.add_column('animals', sa.Column('prefix', mysql.TEXT(), nullable=True))
    op.add_column('animals', sa.Column('romance_profile', mysql.TEXT(), nullable=True))
    op.add_column('animals', sa.Column('so_profile', mysql.TEXT(), nullable=True))
    op.add_column('animals', sa.Column('tags', LaboratoryTypes.TextTuple(), nullable=True))
    op.drop_column('mbti_questions', 'positive')
    op.add_column('users', sa.Column('ideal_age_end', mysql.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ideal_age_start', mysql.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ideal_body_shape', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('ideal_height_end', mysql.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ideal_height_start', mysql.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ideal_type_groups', LaboratoryTypes.IntTuple(), nullable=True))
    op.add_column('users', sa.Column('personality', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('registration_confirmed', sa.BOOLEAN(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('registration_confirmed_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('registration_phase', mysql.CHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('type_group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'type_groups', ['type_group'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['personality'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'type_group')
    op.drop_column('users', 'registration_phase')
    op.drop_column('users', 'registration_confirmed_at')
    op.drop_column('users', 'registration_confirmed')
    op.drop_column('users', 'personality')
    op.drop_column('users', 'ideal_type_groups')
    op.drop_column('users', 'ideal_height_start')
    op.drop_column('users', 'ideal_height_end')
    op.drop_column('users', 'ideal_body_shape')
    op.drop_column('users', 'ideal_age_start')
    op.drop_column('users', 'ideal_age_end')
    op.add_column('mbti_questions', sa.Column('positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('animals', 'tags')
    op.drop_column('animals', 'so_profile')
    op.drop_column('animals', 'romance_profile')
    op.drop_column('animals', 'prefix')
    op.drop_column('animals', 'main_profile')
    op.drop_table('occupation_auth')
    op.drop_table('type_groups')
    # ### end Alembic commands ###
