"""05_11_3

Revision ID: f458918a525a
Revises: 0bfa0d9fa905
Create Date: 2020-05-11 15:46:23.043189

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f458918a525a'
down_revision = '0bfa0d9fa905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.TEXT(), nullable=True),
    sa.Column('third_party_token', mysql.TEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiry', mysql.DATETIME(), nullable=False),
    sa.Column('activated', sa.Integer(), server_default='1', nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
