"""0623_el_time

Revision ID: ffdef0352b0d
Revises: 399aee118a81
Create Date: 2020-06-23 15:50:57.588519

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import LaboratoryTypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffdef0352b0d'
down_revision = '399aee118a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('type_', mysql.CHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('el_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'el_time')
    op.drop_column('matches', 'type_')
    # ### end Alembic commands ###
