apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sy-ingress
  namespace: sy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "sy-ip"
    networking.gke.io/managed-certificates: sy-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: sy-prod
          servicePort: 8000
      - path: /admin
        backend:
          serviceName: sy-admin
          servicePort: 8000
#      - path: /console
#        backend:
#          serviceName: sy-console
#          servicePort: 80
