apiVersion: v1
kind: Service
metadata:
  labels:
    run: sy-prod-admin
  name: sy-prod-admin
  namespace: sy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: sy-prod-admin
  type: NodePort
