openapi: 3.0.0

info:
  version: '1.0'
  title: 'Laboratory S'
  description: 'Laboratory S API'

servers:
  - description: Local
    url: http://localhost:8000/

paths:
  /:
    $ref: 'rest/health.yaml#/hi'

  # Oauth
  /oauth/google:
    $ref: 'rest/oauth.yaml#/google'
#  /oauth/naver:
#    $ref: 'rest/oauth.yaml#/naver'
  /oauth/kakao:
    $ref: 'rest/oauth.yaml#/kakao'
#  /oauth/apple:
#    $ref: 'rest/oauth.yaml#/apple'

  # Users
  /users/{user_id}:
    $ref: 'rest/user.yaml#/profile'
  /users/me:
    $ref: 'rest/user.yaml#/me'
  /users/nickname/{nick_name}:
    $ref: 'rest/user.yaml#/nickname'

  # Sms
  /sms:
    $ref: 'rest/sms.yaml#/sms'
  /sms/auth:
    $ref: 'rest/sms.yaml#/sms_auth'

  # Mbti
  /mbti:
    $ref: 'rest/mbti.yaml#/mbti'

  # Term
  /terms:
    $ref: 'rest/term.yaml#/term'

  # Magazines
#  /magazines:
#    $ref: 'rest/magazine.yaml#/magazines'

components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.login_required
  schemas:
    user:
      $ref: 'models/user.yaml#/user'
    term:
      $ref: 'models/term.yaml#/term'
    terms_agreement:
      $ref: 'models/terms_agreement.yaml#/terms_agreement'
