openapi: 3.0.0

info:
  version: '1.0'
  title: 'Laboratory S'
  description: 'Laboratory S API'

servers:
  - description: Local
    url: http://localhost:8000/

paths:
  /:
    $ref: 'rest/health.yaml#/hi'

  # Oauth
  /oauth/google:
    $ref: 'rest/oauth.yaml#/google'
  /oauth/naver:
    $ref: 'rest/oauth.yaml#/naver'
  /oauth/kakao:
    $ref: 'rest/oauth.yaml#/kakao'
#  /oauth/apple:
#    $ref: 'rest/oauth.yaml#/apple'

  # Users
  /users/{user_id}:
    $ref: 'rest/user.yaml#/profile'
  /users/me:
    $ref: 'rest/user.yaml#/me'
  /users/nickname/{nick_name}:
    $ref: 'rest/user.yaml#/nickname'
  /users/occupation:
    $ref: 'rest/user.yaml#/occupation'

  # Heart
  /heart:
    $ref: 'rest/heart.yaml#/heart'
  /heart/double:
    $ref: 'rest/heart.yaml#/double_heart'
  /heart/recharge/google:
    $ref: 'rest/heart.yaml#/google_recharge'

  # Star
  /star:
    $ref: 'rest/star.yaml#/star'

  # Sms
  /sms:
    $ref: 'rest/sms.yaml#/sms'
  /sms/auth:
    $ref: 'rest/sms.yaml#/sms_auth'

  # Animals
  /animals/{animal_id}:
    $ref: 'rest/animal.yaml#/animal'

  # Questions
  /questions/mbti:
    $ref: 'rest/question.yaml#/mbti'
#  /questions/love:
#    $ref: 'rest/question.yaml#/mbti'

  # Term
  /terms:
    $ref: 'rest/term.yaml#/term'

  # Image
  /image:
    $ref: 'rest/image.yaml#/image'

  # Type Group
  /type_groups/{type_group_id}:
    $ref: 'rest/type_group.yaml#/type_group'
  /type_groups:
    $ref: 'rest/type_group.yaml#/type_groups'

  # Magazines
#  /magazines:
#    $ref: 'rest/magazine.yaml#/magazines'

components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.login_required
  schemas:
    animal:
      $ref: 'models/animal.yaml#/animal'
    user:
      $ref: 'models/user.yaml#/user'
    term:
      $ref: 'models/term.yaml#/term'
    terms_agreement:
      $ref: 'models/terms_agreement.yaml#/terms_agreement'
    sms:
      $ref: 'models/sms_auth.yaml#/sms_auth'
    mbti_question:
      $ref: 'models/mbti_question.yaml#/mbti_question'
    type_group:
      $ref: 'models/type_group.yaml#/type_group'
