openapi: 3.0.0

info:
  version: '1.0'
  title: 'Laboratory S Admin'
  description: 'Laboratory S Admin'

servers:
  - description: Local
    url: http://localhost:8000/

paths:
  /:
    $ref: 'rest/health.yaml#/hi'


  # Admin
  /admin/auth:
    $ref: 'rest/admin.yaml#/auth'
  /admin/info:
    $ref: 'rest/admin.yaml#/info'

  # Users
  /users:
    $ref: 'rest/user.yaml#/users'
  /users/{id_}:
    $ref: 'rest/user.yaml#/user'

  # Animals
  /animals:
    $ref: 'rest/animal.yaml#/animal'



components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.admin_required
